export enum ProcessStateCode {
  UninterruptibleSleep = 'D',
  Running = 'R',
  InterruptibleSleep = 'S',
  Stopped = 'T',
  Paging = 'W',
  Dead = 'X',
  Zombie = 'Z',
  Idle = 'I',
  HighPriority = '<',
  LowPriority = 'N',
  PagesLocked = 'L',
  SessionLeader = 's',
  MultiThreaded = 'l',
  Foreground = '+',
}
