import { IProcessTableColumn } from '../models';

export const PROCESS_TABLE_COLUMNS: { [prop: string]: IProcessTableColumn } = {
  name: {
    index: 0,
    name: 'Name',
    prop: 'name',
    width: 300,
    sortable: true,
    filterable: true,
    isTreeColumn: true,
    visible: true,
    treeLevelIndent: 20,
  },
  user: {
    index: 1,
    name: 'User',
    prop: 'user',
    width: 80,
    sortable: true,
    filterable: true,
    visible: true,
  },
  pcpu: {
    index: 2,
    name: 'CPU %',
    prop: 'pcpu',
    width: 80,
    sortable: true,
    visible: true,
  },
  pmem: {
    index: 3,
    name: 'Memory %',
    prop: 'pmem',
    width: 80,
    sortable: true,
    visible: true,
  },
  priority: {
    index: 4,
    name: 'Priority',
    prop: 'priority',
    width: 80,
    sortable: true,
  },
  mem_rss: {
    index: 5,
    name: 'RSS',
    prop: 'mem_rss',
    width: 80,
    sortable: true,
  },
  mem_vsz: {
    index: 6,
    name: 'VSZ',
    prop: 'mem_vsz',
    width: 80,
    sortable: true,
  },
  pid: {
    index: 7,
    name: 'PID',
    prop: 'pid',
    width: 80,
    sortable: true,
    filterable: true,
  },
  state: {
    index: 9,
    name: 'Status',
    prop: 'state',
    width: 100,
    sortable: true,
  },
  started: {
    index: 11,
    name: 'Started',
    prop: 'started',
    width: 200,
    sortable: true,
    visible: true,
  },
};
